name: End-to-End tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
          - name: Page Speed Insights
            uses: JakePartusch/psi-action@v1.3
            with:
               url: "https://www.reddit.com/"
               threshold: 30
               strategy: mobile
